name: goph_keeper
services: 
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: goph_keeper
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: goph_keeper
    ports: 
      - "5433:5432"
    networks:
      - backend
  app:
    image: goph_keeper:latest
    restart: always
    build:
      context: .
      dockerfile: goph_keeper.Dockerfile
    environment:
      SERVER_ADDRESS: app:8080
      DATABASE_URI: postgresql://goph_keeper:12345678@db:5432/goph_keeper?sslmode=disable
      LOG_LEVEL: INFO
      # S3_ENDPOINT: play.min.io:9000
      # S3_ACCESS_KEY_ID: Q3AM3UQ867SPQQA43P2F
      # S3_SECRET_ACCESS_KEY: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      # S3_BACKET_NAME: testbucket1234
      # S3_USE_SSL: true
      # S3_SECURE_FILES: true
      S3_ENDPOINT: s3:9000
      S3_ACCESS_KEY_ID: superroot
      S3_SECRET_ACCESS_KEY: password
      S3_BACKET_NAME: testbucket1234
      S3_USE_SSL: false
      S3_SECURE_FILES: false
    depends_on:
      - db
      # - s3
    ports: 
      - "8080:8080"
    networks:
      - backend
  s3:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: superroot
      MINIO_ROOT_PASSWORD: password
    ports: 
      - "9000:9000"
      - "9001:9001"
    command: 'server /data --console-address ":9001"'
    networks:
      - backend
networks:
  backend: 
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 10.15.32.0/24
