name: go vet test

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  statictest:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
